### ISSUE TITLE
Feature request: Centralized locales and web configurator

### ISSUE THREAD

**Issue by ghost** [rcarvello/webmvcframework#3]
Hello Rosario,

Going through scripts, I found that the locale scripts are spread out two directories. I suggest to have it in only in one directory. Then one could have two sub-directories, one sub-directory could be generic for general purpose used by the system calls and second sub-directory could be to have it relative to templates and views, etc. 

It would also help to have a language manager to configure, add and edit language files from the web interface. Then it becomes easy to copy existing default language and then translate.

**Comment by rcarvello** [comment]
Hello and thanks for your question.

The framework uses a subdirectory of "locales",  for storing translation of every language you need.
For example 'locales/en' for English, 'locales/it-it' for Italian. You can add more subdirectories depending on the number of the translations you need. The name of this subdirectory must match the LCID: see  https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes for Locales Code ID

By Considering, for examples, the "en" subdirectory,  you can find inside of it another directory: "controllers" which reflects the same structure of the root "controllers" directory where you code your Controllers.  You also find different text files (containing the translations) with the same name of your Controllers Classes you need to translate.

The framework uses the same directory structure in different directory levels: models, views, controllers, templates, locales (and more in the future version).
See: https://github.com/rcarvello/webmvcframework/wiki/Understanding-WebMVC

Note:
In addition, you can find the file "application.txt" at the root level of "en" subdirectory where you can put translations shared among different controllers.

**Comment by ghost** [comment]
Hello Rosario,

Thanks for the answer and taking time to read my feature request. 

My question was: 
> Can the language files in /framework/locales/* and /locales/* be combined to be under one global directory as /locales/framework/* and /locales/templates/*. With this, one could have everything under one directory /locales/*.

Because your answer implies that you do not want to change it indirectly, I close this request.

**Comment by rcarvello** [comment]
`/locales/framework/` is a built-in directory for translations about  framework features such as components

`/locales/` is the directory where to store 'YOUR APPLICATION' translation

> Can the language files in /framework/locales/* and /locales/* be combined to be under one global directory as /locales/framework/* and /locales/templates/. With this, one could have everything under one directory /locales/.

YES , you can do it in this way:

> Note:
> In addition, you can find the file "application.txt" at the root level of "en" subdirectory where you can put translations shared among different controllers.

You can use` locales/LCID/application.txt`  for storing in one place the translations about all your Controllers.

Example:

- `locales/en/application.txt` for storing English translations
- `locales/it-it/application.txt` for storing Italian translations
and so on.

Any time you execute a Controller, for example `home ` controller, framework use many translation files in the order.

1. framework/locales/LCID/framework.txt (first loaded)
2. locales/LCID/application.txt (the second)
3. locales/en/controllers/Home.txt (the last, current running controller)

You can decide to put all your translation in 2 and omit to store translation in 1 and 3

**Comment by rcarvello** [comment]
I forgot.
In `application.txt ` you can also OVERWRITE all the translations that were defined in `framework/locales`

**Comment by ghost** [comment]
Hello Rosario,

Ha, ha, you did not want to implement this because it is already in there built-in. Now is everything clear. Thats lovely to know this. Excellent. Thanks for your reply.
