### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by peter279k** [rcarvello/webmvcframework#5]
I think this package should require the unit tests and it can validate the every class unit to do expected behavior.

And I also suggest that we can consider using the PHPUnit to complete this issue :).

If we want to let the unit tests run automatically on upcoming PR, we can also consider using the Travis CI to complete this.

It makes sure every future upcoming PRs will do the expected behavior.

**Comment by rcarvello** [comment]
https://pacroy.medium.com/why-most-unit-testing-is-waste-tests-dont-improve-quality-developers-do-47a8584f79ab

**Comment by peter279k** [comment]
https://performancelabus.com/unit-testing-importance/

**Comment by peter279k** [comment]
Sometimes tests can be helpful for developers know all code behaviors quickly and find the current bugs correctly.

Closed because author doesn't prefer that.
