### ISSUE TITLE
Using PDO

### ISSUE THREAD

**Issue by ghost** [rcarvello/webmvcframework#6]
I want to stop using **mysqli** and use the extended **PDO** class in the project. How to make?

**Comment by rcarvello** [comment]
You can replace Model class located ad framework/Model.php with something like this
(but I did not tested it, I prefer mysqli)
```
<?php

namespace framework;
class Model extends \PDO
{
    public function __construct($dsn, $username = null, $passwd = null, $options = null)
    {
        parent::__construct("mysql:host=" . DBHOST .";dbname=".DBNAME, DBUSER, DBPASSWORD, $options);
    }
}
```
