### ISSUE TITLE
Undefined constant

### ISSUE THREAD

**Issue by ghost** [rcarvello/webmvcframework#8]
-- English version --
Trying to use the builder I get an undefined constant error. Do you have any idea on how to fix or a specific version of php to use?

-- Italian version --
Tentando di usare il builder ricevo un messaggio di costante non definita. Hai per caso idea di come risolvere o una specifica versione di php da consigliare?

`Warning: Use of undefined constant SECURING_OUTSIDE_HTTP_FOLDER - assumed 'SECURING_OUTSIDE_HTTP_FOLDER' (this will throw an Error in a future version of PHP) in C:\wamp64\www\test\views\builders\SkeletonBuider.php on line 95`

PHP Version: 7.4.15

Ciao

**Comment by rcarvello** [comment]
Hi
Download again config/security.config.php,
I just added on it the missed constant SECURING_OUTSIDE_HTTP_FOLDER

**Comment by ghost** [comment]
Thank you.

Grazie (Sono italiano anche io).
